[package]
name = "macros"
version = "0.1.0"
edition = "2024"

[features]
server = []
client = []

[lib]
proc-macro = true

[dependencies]
cfg-if = "1.0"
proc-macro2 = "1.0.92"
syn = "2.0.93"
quote = "1.0.38"
proc-macro-error = "1.0.4"

session = { path = "../session" }
