[package]
name = "session"
version = "0.1.0"
edition = "2024"

[features]
server = []

[dependencies]
eyre.workspace = true
serde.workspace = true
bitcode.workspace = true
hashbrown.workspace = true

codee = "0.3"
