[package]
name = "session"
version = "0.1.0"
edition = "2021"

[features]
server = []

[dependencies]
bevy.workspace = true
eyre.workspace = true
serde.workspace = true
bitcode.workspace = true

codee = "0.3"
